In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import os
import sklearn
import seaborn as sns
from sklearn.preprocessing import StandardScaler

import optuna
from sklearn.ensemble import VotingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import  OrdinalEncoder
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import StandardScaler

# matplotlib에 한글 폰트 설정
plt.rcParams['font.family'] = 'AppleGothic'  # MacOS용 폰트 설정
plt.rcParams['axes.unicode_minus'] = False

In [48]:
import sys
import os
import pandas as pd

# 현재 작업 디렉토리 경로를 가져와 shared codes 폴더의 위치를 sys.path에 추가합니다.
# sys.path에 추가된 경로에 있는 py 폴더는 임포트할 수 있다.
current_dir = os.getcwd()
shared_codes_dir = os.path.join(current_dir, '../shared codes')
sys.path.append(shared_codes_dir)


# cover_nan 모듈을 임포트
from cover_nan_0224_IVFDI import missing_value_removal_function

# 원본 train 데이터 로드
train = pd.read_csv("../shared codes/data/train.csv")
test = pd.read_csv("../shared codes/data/test.csv")

# missing_value_removal_function 사용
train_IVF, train_DI = missing_value_removal_function(train)
test_IVF, test_DI = missing_value_removal_function(test)

✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!
✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!

In [22]:
# # 현재 작업 디렉토리 경로를 가져와 shared codes 폴더의 위치를 sys.path에 추가합니다.
# # sys.path에 추가된 경로에 있는 py 폴더는 임포트할 수 있다.
# current_dir = os.getcwd()
# shared_codes_dir = os.path.join(current_dir, '../shared codes')
# sys.path.append(shared_codes_dir)

# # cover_nan 모듈을 임포트
# from cover_nan_0215_dahun import missing_value_removal_function

# # 원본 train 데이터 로드
# train = pd.read_csv("../shared codes/data/train.csv")
# test = pd.read_csv("../shared codes/data/test.csv")

# # missing_value_removal_function 사용
# train_young, train_middle, train_old, train_unknown = missing_value_removal_function(train)
# test_young, test_middle, test_old, test_unknown = missing_value_removal_function(test)

In [1]:
import sys
import os
import pandas as pd

# 현재 작업 디렉토리 경로를 가져와 shared codes 폴더의 위치를 sys.path에 추가합니다.
# sys.path에 추가된 경로에 있는 py 폴더는 임포트할 수 있다.
current_dir = os.getcwd()
shared_codes_dir = os.path.join(current_dir, '../shared codes')
sys.path.append(shared_codes_dir)


# cover_nan 모듈을 임포트
from cover_nan_0224_age_IVFDI import missing_value_removal_function

# 원본 train 데이터 로드
train = pd.read_csv("../shared codes/data/train.csv")
test = pd.read_csv("../shared codes/data/test.csv")

# missing_value_removal_function 사용
train_young_IVF, train_young_DI, train_middle_IVF, train_middle_DI, train_old_IVF, train_old_DI, train_unknown, train_0 = missing_value_removal_function(train)
test_young_IVF, test_young_DI, test_middle_IVF, test_middle_DI, test_old_IVF, test_old_DI, test_unknown, test_0 = missing_value_removal_function(test)

✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!
✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!

In [23]:
def data_preprocessing(train, test):
    index_train = train['idx']
    X = train.drop(['임신 성공 여부', 'idx'], axis=1)
    y = train['임신 성공 여부']

    index_test = test['idx'].copy()  # Ensure a copy is made to prevent any shared memory issues
    test = test.drop('idx', axis=1)

    # 불필요한 칼럼 삭제
    columns_to_drop = [
        "남성 주 불임 원인",
        "남성 부 불임 원인",
        "불임 원인 - 정자 농도",
        "불임 원인 - 정자 면역학적 요인",
        "불임 원인 - 정자 운동성",
        "불임 원인 - 정자 형태",
        '배란 유도 유형'
    ]
    X_train_reduced = X.drop(columns=columns_to_drop)    
    X_test_reduced = test.drop(columns=columns_to_drop)

    numeric_features = [
        '총 생성 배아 수',
        '미세주입된 난자 수',
        '미세주입에서 생성된 배아 수',
        '이식된 배아 수',
        '미세주입 배아 이식 수',
        '저장된 배아 수',
        '미세주입 후 저장된 배아 수',
        '해동된 배아 수',
        '해동 난자 수',
        '수집된 신선 난자 수',
        '저장된 신선 난자 수',
        '혼합된 난자 수',
        '파트너 정자와 혼합된 난자 수',
        '기증자 정자와 혼합된 난자 수',
        '난자 혼합 경과일',
        '배아 이식 경과일'
    ]   
    
    # 데이터 정규화 (수치형 데이터만 정규화)
    # numeric_features = X_train_reduced.select_dtypes(include=[np.number]).columns
    scaler = StandardScaler()
    X_train_scaled = X_train_reduced.copy()
    X_test_scaled = X_test_reduced.copy()
    X_train_scaled[numeric_features] = scaler.fit_transform(X_train_reduced[numeric_features])
    X_test_scaled[numeric_features] = scaler.transform(X_test_reduced[numeric_features])

    # 인덱스 추가
    X_train_scaled['idx'] = index_train.reset_index(drop=True)
    X_test_scaled['idx'] = index_test.reset_index(drop=True)

    return X_train_scaled, X_test_scaled, y

In [24]:
from catboost import CatBoostClassifier
import pandas as pd

def train_catboost_model(X_train_scaled, y, X_test_scaled):
    # CatBoost 모델 정의
    model = CatBoostClassifier(
        iterations=1000,
        depth=6,
        learning_rate=0.1,
        loss_function='Logloss',
        verbose=100,
        random_seed=42
    )

    # 모델 학습
    model.fit(X_train_scaled, y)

    # 예측 확률
    pred_proba = model.predict_proba(X_test_scaled)[:, 1]

    # 제출용 데이터프레임 생성
    submission = pd.DataFrame({
        'probability': pred_proba,
        'idx': X_test_scaled['idx']
    })

    return submission

In [25]:
# '단일 배아 이식 여부' == 1이고 '이식된 배아 수' > 0인 행 필터링
single_embryo_rows = test[(test['단일 배아 이식 여부'] == 1) & (test['이식된 배아 수'] != 1)]





# 필터링된 결과 출력
print(single_embryo_rows[['총 생성 배아 수', '이식된 배아 수', '단일 배아 이식 여부', '난자 출처', '정자 출처']])

       총 생성 배아 수  이식된 배아 수  단일 배아 이식 여부  난자 출처   정자 출처
41552       10.0       2.0          1.0  본인 제공  배우자 제공
59077        0.0       2.0          1.0  본인 제공  배우자 제공
66507       13.0       2.0          1.0  본인 제공  배우자 제공
82710        7.0       2.0          1.0  본인 제공  배우자 제공
86539        0.0       2.0          1.0  본인 제공  배우자 제공

In [26]:
train[['총 생성 배아 수', '이식된 배아 수']]

        총 생성 배아 수  이식된 배아 수
0             4.0       2.0
1             0.0       0.0
2             5.0       2.0
3             0.0       0.0
4             6.0       2.0
...           ...       ...
256346        5.0       2.0
256347        3.0       2.0
256348        6.0       2.0
256349        2.0       2.0
256350        0.0       2.0

[256351 rows x 2 columns]

In [27]:
import pandas as pd
import numpy as np

def print_correlation_with_target(dataframe, target_column):
    # 수치형 데이터만 선택
    numeric_df = dataframe.select_dtypes(include=[np.number])
    
    # 타겟 컬럼과의 상관계수 계산
    target_correlations = numeric_df.corr()[target_column].drop(target_column)  # 타겟 자신 제외

    # 상관계수 출력
    print(f"'{target_column}' 컬럼과 다른 수치형 컬럼 간의 상관계수:")
    for column_name, correlation_value in target_correlations.items():
        if abs(correlation_value) >= 0.1:
            print(f"{column_name}: {correlation_value:.4f}")

# 데이터 프레임 설정 (예시로 X_train_encoded_young를 사용)
# df = X_train_encoded_young  # 실제 데이터를 사용할 때 주석 해제

# 상관계수 출력
print_correlation_with_target(train, '이식된 배아 수')

'이식된 배아 수' 컬럼과 다른 수치형 컬럼 간의 상관계수:
단일 배아 이식 여부: -0.2629
착상 전 유전 진단 사용 여부: -0.1013
미세주입 배아 이식 수: 0.4897
저장된 배아 수: -0.2925
미세주입 후 저장된 배아 수: -0.2101
저장된 신선 난자 수: -0.1434
임신 성공 여부: 0.1575

In [28]:
interest_col = [
    '이식된 배아 수',
    '저장된 배아 수',
    '단일 배아 이식 여부',
    '혼합된 난자 수',
    '총 생성 배아 수',
    '배아 생성 주요 이유',
    '미세주입에서 생성된 배아 수',
    '미세주입 배아 이식 수',
    '저장된 배아 수',
    '미세주입 후 저장된 배아 수',
    '동결 배아 사용 여부',
    '신선 배아 사용 여부',
    '기증 배아 사용 여부'
]

df = train[interest_col]

In [29]:
import sys
import os
import pandas as pd

# 현재 작업 디렉토리 경로를 가져와 shared codes 폴더의 위치를 sys.path에 추가합니다.
# sys.path에 추가된 경로에 있는 py 폴더는 임포트할 수 있다.
current_dir = os.getcwd()
shared_codes_dir = os.path.join(current_dir, '../shared codes')
sys.path.append(shared_codes_dir)


# cover_nan 모듈을 임포트
from cover_nan import missing_value_removal_function

# 원본 train 데이터 로드
train = pd.read_csv("../shared codes/data/train.csv")

# missing_value_removal_function 사용
df = missing_value_removal_function(train)

✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!

In [30]:
# print(train['파트너 정자와 혼합된 난자 수'].value_counts())
# print(train['혼합된 난자 수'].value_counts())
# print(train['기증자 정자와 혼합된 난자 수'].value_counts())

# df = train.copy()
# # # 조건을 만족하지 않는 행을 선택하여 필터링 (즉, 파트너 정자와 혼합된 난자 수가 혼합된 난자 수보다 큰 경우)
# # filtered_df = df[~(df['파트너 정자와 혼합된 난자 수'] <= df['혼합된 난자 수'])][['파트너 정자와 혼합된 난자 수', '혼합된 난자 수']]

# # # 결과 출력
# # print(filtered_df)
# # df['파트너 혼합 - 그냥 혼합'] = df['파트너 정자와 혼합된 난자 수'] < df['혼합된 난자 수']
# # print(df['파트너 혼합 - 그냥 혼합'].value_counts())
# train['파트너 정자와 혼합된 난자 수'].isna().sum()

# print(df[df['혼합된 난자 수'] != df['파트너 정자와 혼합된 난자 수'] + df['기증자 정자와 혼합된 난자 수']][['혼합된 난자 수']].value_counts())
# print(df[df['혼합된 난자 수'] != df['파트너 정자와 혼합된 난자 수'] + df['기증자 정자와 혼합된 난자 수']][['파트너 정자와 혼합된 난자 수']].value_counts())
# print(df[df['혼합된 난자 수'] != df['파트너 정자와 혼합된 난자 수'] + df['기증자 정자와 혼합된 난자 수']][['기증자 정자와 혼합된 난자 수']].value_counts())
# print(df[df['혼합된 난자 수'] != df['파트너 정자와 혼합된 난자 수'] + df['기증자 정자와 혼합된 난자 수']][['정자 출처']].value_counts())
temp = df[df['혼합된 난자 수'] != df['파트너 정자와 혼합된 난자 수'] + df['기증자 정자와 혼합된 난자 수']]
temp[temp['기증자 정자와 혼합된 난자 수'] == 0]['혼합된 난자 수'].value_counts()
temp[temp['기증자 정자와 혼합된 난자 수'] == 0]['시술 유형'].value_counts()


# train[train['기증자 정자와 혼합된 난자 수'] != 0]['시술 유형'].value_counts()

시술 유형
IVF    874
Name: count, dtype: int64

In [31]:
train[(train['파트너 정자와 혼합된 난자 수'] != 0) & (train['기증자 정자와 혼합된 난자 수'] != 0)][['혼합된 난자 수', '파트너 정자와 혼합된 난자 수', '기증자 정자와 혼합된 난자 수']]

        혼합된 난자 수  파트너 정자와 혼합된 난자 수  기증자 정자와 혼합된 난자 수
14           NaN               NaN               NaN
39           NaN               NaN               NaN
96          22.0              11.0              11.0
127          NaN               NaN               NaN
162          NaN               NaN               NaN
...          ...               ...               ...
256222       NaN               NaN               NaN
256228       NaN               NaN               NaN
256301       NaN               NaN               NaN
256326       NaN               NaN               NaN
256345      13.0               7.0               6.0

[6408 rows x 3 columns]

In [32]:
print(train['난자 출처'].value_counts())

my_nanja = train[train['난자 출처'] == '본인 제공']
donated_nanja = train[train['난자 출처'] == '기증 제공']

난자 출처
본인 제공     234291
기증 제공      15769
알 수 없음      6291
Name: count, dtype: int64

In [33]:
print(my_nanja['정자 출처'].value_counts())
print()
print(donated_nanja['정자 출처'].value_counts())

정자 출처
배우자 제공         216812
기증 제공           17357
미할당               108
배우자 및 기증 제공        14
Name: count, dtype: int64

정자 출처
배우자 제공    12387
기증 제공      3368
미할당          14
Name: count, dtype: int64

In [1]:
import sys
import os
import pandas as pd

# 현재 작업 디렉토리 경로를 가져와 shared codes 폴더의 위치를 sys.path에 추가합니다.
# sys.path에 추가된 경로에 있는 py 폴더는 임포트할 수 있다.
current_dir = os.getcwd()
shared_codes_dir = os.path.join(current_dir, '../shared codes')
sys.path.append(shared_codes_dir)


# cover_nan 모듈을 임포트
from cover_nan import missing_value_removal_function

# 원본 train 데이터 로드
train = pd.read_csv("../shared codes/data/train.csv")

# missing_value_removal_function 사용
df = missing_value_removal_function(train)

✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!

In [2]:
df_IVF = df[df['시술 유형'] == "IVF"]
df_DI = df[df['시술 유형'] == "DI"]

In [6]:
df_IVF['특정 시술 유형'].value_counts()

특정 시술 유형
ICSI                                   122370
IVF                                     91755
Unknown                                 26939
ICSI:ICSI                                2314
ICSI / BLASTOCYST                        1609
IVF / BLASTOCYST                         1248
IVF:IVF                                  1146
ICSI:IVF                                  873
ICSI / AH                                 769
IVF:ICSI                                  392
IVF / AH                                  319
ICSI:Unknown                              207
IVF:Unknown                               100
ICSI / BLASTOCYST:IVF / BLASTOCYST          6
ICSI / BLASTOCYST :IVF / BLASTOCYST         4
FER                                         3
IVF / AH:ICSI / AH                          2
ICSI / AH:Unknown                           2
ICSI / BLASTOCYST :ICSI                     1
GIFT                                        1
Name: count, dtype: int64

In [5]:
df_IVF[['특정 시술 유형', '임신 성공 여부']].value_counts()

특정 시술 유형                             임신 성공 여부
ICSI                                 0           88985
IVF                                  0           67765
ICSI                                 1           33385
IVF                                  1           23990
Unknown                              0           20549
                                     1            6390
ICSI:ICSI                            0            2291
IVF:IVF                              0            1134
ICSI / BLASTOCYST                    0            1035
IVF / BLASTOCYST                     0             791
ICSI:IVF                             0             668
ICSI / AH                            0             602
ICSI / BLASTOCYST                    1             574
IVF / BLASTOCYST                     1             457
IVF:ICSI                             0             281
IVF / AH                             0             260
ICSI:IVF                             1             205
ICSI:Unknown                         0             186
ICSI / AH                            1             167
IVF:ICSI                             1             111
IVF:Unknown                          0              83
IVF / AH                             1              59
ICSI:ICSI                            1              23
ICSI:Unknown                         1              21
IVF:Unknown                          1              17
IVF:IVF                              1              12
ICSI / BLASTOCYST:IVF / BLASTOCYST   0               4
ICSI / BLASTOCYST :IVF / BLASTOCYST  0               3
FER                                  0               2
IVF / AH:ICSI / AH                   0               2
ICSI / BLASTOCYST:IVF / BLASTOCYST   1               2
ICSI / AH:Unknown                    0               1
                                     1               1
FER                                  1               1
ICSI / BLASTOCYST :IVF / BLASTOCYST  1               1
GIFT                                 0               1
ICSI / BLASTOCYST :ICSI              1               1
Name: count, dtype: int64

In [9]:
df[df['특정 시술 유형'] != "ICSI"]['미세주입 배아 이식 수'].value_counts()

미세주입 배아 이식 수
0.0    130565
1.0      1744
2.0      1449
3.0       223
Name: count, dtype: int64

In [25]:
# df_DI의 unique한 값이 1개인 컬럼 확인
DI_col = df_DI.columns

unique_1_col_DI = []
for col in DI_col:
    if df_DI[col].unique().shape[0] == 1:
        unique_1_col_DI.append(col)
        print(df_DI[col].value_counts())
        print()


print(unique_1_col_DI)
print(len(unique_1_col_DI))

df_DI = df_DI.drop(columns=unique_1_col_DI)



# df_IVF의 unique한 값이 1개인 컬럼 확인
# IVF_col = df_IVF.columns

# unique_1_col_IVF = []
# for col in IVF_col:
#     if df_IVF[col].unique().shape[0] == 1:
#         unique_1_col_IVF.append(col)
#         print(df_IVF[col].value_counts())
#         print()

# print(unique_1_col_IVF)
# print(len(unique_1_col_IVF))

시술 유형
DI    6291
Name: count, dtype: int64

배란 유도 유형
알 수 없음    6291
Name: count, dtype: int64

단일 배아 이식 여부
0.0    6291
Name: count, dtype: int64

불임 원인 - 여성 요인
0    6291
Name: count, dtype: int64

불임 원인 - 자궁경부 문제
0    6291
Name: count, dtype: int64

불임 원인 - 정자 면역학적 요인
0    6291
Name: count, dtype: int64

불임 원인 - 정자 운동성
0    6291
Name: count, dtype: int64

배아 생성 주요 이유
1    6291
Name: count, dtype: int64

총 생성 배아 수
0.0    6291
Name: count, dtype: int64

미세주입된 난자 수
0.0    6291
Name: count, dtype: int64

미세주입에서 생성된 배아 수
0.0    6291
Name: count, dtype: int64

이식된 배아 수
0.0    6291
Name: count, dtype: int64

미세주입 배아 이식 수
0.0    6291
Name: count, dtype: int64

저장된 배아 수
0.0    6291
Name: count, dtype: int64

미세주입 후 저장된 배아 수
0.0    6291
Name: count, dtype: int64

해동된 배아 수
0.0    6291
Name: count, dtype: int64

해동 난자 수
0.0    6291
Name: count, dtype: int64

수집된 신선 난자 수
0.0    6291
Name: count, dtype: int64

저장된 신선 난자 수
0.0    6291
Name: count, dtype: int64

혼합된 난자 수
0.0    6291
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

Series([], Name: count, dtype: int64)

난자 출처
알 수 없음    6291
Name: count, dtype: int64

정자 출처
기증 제공    6291
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

Series([], Name: count, dtype: int64)

Series([], Name: count, dtype: int64)

대리모 여부
0.0    6291
Name: count, dtype: int64

난자 채취 경과일
0.0    6291
Name: count, dtype: int64

난자 혼합 경과일
0.0    6291
Name: count, dtype: int64

배아 이식 경과일
3.0    6291
Name: count, dtype: int64

['시술 유형', '배란 유도 유형', '단일 배아 이식 여부', '불임 원인 - 여성 요인', '불임 원인 - 자궁경부 문제', '불임 원인 - 정자 면역학적 요인', '불임 원인 - 정자 운동성', '배아 생성 주요 이유', '총 생성 배아 수', '미세주입된 난자 수', '미세주입에서 생성된 배아 수', '이식된 배아 수', '미세주입 배아 이식 수', '저장된 배아 수', '미세주입 후 저장된 배아 수', '해동된 배아 수', '해동 난자 수', '수집된 신선 난자 수', '저장된 신선 난자 수', '혼합된 난자 수', '파트너 정자와 혼합된 난자 수', '기증자 정자와 혼합된 난자 수', '난자 출처', '정자 출처', '동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', '난자 채취 경과일', '난자 혼합 경과일', '배아 이식 경과일']
31

In [26]:
df_DI.columns

Index(['ID', '시술 시기 코드', '시술 당시 나이', '특정 시술 유형', '배란 자극 여부', '남성 주 불임 원인',
       '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인',
       '불명확 불임 원인', '불임 원인 - 난관 질환', '불임 원인 - 남성 요인', '불임 원인 - 배란 장애',
       '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도', '불임 원인 - 정자 형태', '총 시술 횟수',
       '클리닉 내 총 시술 횟수', 'IVF 시술 횟수', 'DI 시술 횟수', '총 임신 횟수', 'IVF 임신 횟수',
       'DI 임신 횟수', '총 출산 횟수', 'IVF 출산 횟수', 'DI 출산 횟수', '난자 기증자 나이',
       '정자 기증자 나이', '임신 성공 여부'],
      dtype='object')

In [10]:
df[df['미세주입 배아 이식 수'] == 0]['특정 시술 유형'].value_counts()

특정 시술 유형
IVF                   91755
Unknown               26939
ICSI                  14500
IUI                    6100
ICSI:ICSI              2197
IVF / BLASTOCYST       1248
IVF:IVF                1146
IVF / AH                319
ICSI:IVF                280
IVF:ICSI                151
IVF:Unknown             100
ICI                      96
Generic DI               71
ICSI:Unknown             64
ICSI / BLASTOCYST        54
IVI                      23
ICSI / AH                15
FER                       3
GIFT                      2
IVF / AH:ICSI / AH        1
ICSI / AH:Unknown         1
Name: count, dtype: int64

In [27]:
import os
import pandas as pd

# 현재 작업 디렉토리 경로를 가져와 shared codes 폴더의 위치를 sys.path에 추가합니다.
# sys.path에 추가된 경로에 있는 py 폴더는 임포트할 수 있다.
current_dir = os.getcwd()
shared_codes_dir = os.path.join(current_dir, '../shared codes')
sys.path.append(shared_codes_dir)


# cover_nan 모듈을 임포트
from cover_nan_0224_age_IVFDI import missing_value_removal_function

# 원본 train 데이터 로드
train = pd.read_csv("../shared codes/data/train.csv")
test = pd.read_csv("../shared codes/data/test.csv")

# missing_value_removal_function 사용
train_young_IVF, train_young_DI, train_middle_IVF, train_middle_DI, train_old_IVF, train_old_DI, train_unknown, train_0 = missing_value_removal_function(train)
test_young_IVF, test_young_DI, test_middle_IVF, test_middle_DI, test_old_IVF, test_old_DI, test_unknown, test_0 = missing_value_removal_function(test)

✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!
✅ '대리모 여부' 결측값을 최빈값 (0.0) 으로 대체 완료!
✅ 컬럼 삭제 완료: ['PGD 시술 여부', 'PGS 시술 여부', '난자 해동 경과일', '배아 해동 경과일']
✅ '난자 채취 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '난자 혼합 경과일' 결측값을 중앙값 (0.0) 으로 대체 완료!
✅ '배아 이식 경과일' 결측값을 중앙값 (3.0) 으로 대체 완료!